name: Update

on:
  workflow_dispatch:
  schedule:
  - cron: "40 * * * *"

jobs:
  update:
    name: Update
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install ldnsutils golang-go sqlite3
      - run: go install github.com/monoidic/dns-tools@latest
      - run: ./scan.sh prework
      - run: ./scan.sh axfr
      - run: ./scan.sh zonefiles
      - run: ./scan.sh md
      - run: git config user.name github-actions && git config user.email github-actions[bot]@users.noreply.github.com
      - run: git add transferable_zones.md archives/ && git commit -m 'Updating zone information' && git push
