name: Update

on:
  workflow_dispatch:
  schedule:
  - cron: "0 23 * * *"

jobs:
  update:
    name: Update
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          persist-credentials: true
      - run: sudo sh -c 'apt update && apt install ldnsutils golang-go sqlite3'
      - run: go install github.com/monoidic/dns-tools@latest
      - run: ./scan.sh prework
      - run: ./scan.sh axfr
      - run: ./scan.sh zonefiles
      - run: ./scan.sh walkable
      - run: ./scan.sh md_axfr
      - run: ./scan.sh md_walkable
      - run: git config user.name github-actions && git config user.email github-actions[bot]@users.noreply.github.com
      - run: git add transferable_zones.md walkable_zones.md archives/ && git commit -m 'Updating zone information' && git push
